version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "07:00"
      timezone: "Europe/Kyiv"
    labels:
      - dependencies
