version: 2

jobs:
  build:
    docker:
      - image: cn007b/go:1.19-alpine

    working_directory: /go/src/github.com/thepkg/awsl

    steps:
      - checkout

      - run: go mod download
      - run: go mod vendor

      - run: go vet
      - run: go fmt ./...
      - run: golint ./...
      - run: golangci-lint run
      - run: gosec -tests ./...

      - run: go test -v -covermode=count -coverprofile=coverage.out
