name: CI

on:
  push:
    branches: [ master, '**' ]
  pull_request:
    branches: [ master, '**' ]
  workflow_dispatch:

jobs:
  check-go-code:
    name: "Check go code"
    runs-on: ubuntu-latest

    steps:
    - name: "Check out"
      uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: "Format"
      run: go fmt ./...

    - name: "Vet"
      run: go vet ./...

    - name: "Lint"
      uses: golangci/golangci-lint-action@v3
      with:
        args: .
