name: "Dependency Review"

on:
  push:
    branches: [ master, '**' ]
  pull_request:
    branches: [ master, '**' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v2
